sudo: required
language: java
jdk:
  - oraclejdk8
branches:
 only:
  - master
install: mvn clean install -DskipTests=true
script: mvn test -P acceptance
after_success:
  - mvn cobertura:cobertura coveralls:report -DrepoToken=$repoToken -DtravisJobId=$TRAVIS_JOB_ID
notifications:
  email:
  - info@ignapzs.net